# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f076d18040fcf8f0e0dc337a27a974f4cffdad2fbe9e830bcb5f836873c0c8196f82abaaf24e5de03c3d1012e9fc5403360a9cea5ce582d66a227642ebf1b6a2

test:
  secret_key_base: 8a17a2525899e737d875bc23ba25b9d8adbf4fae2452422eab103b6b8094431b03e84d7d3d5f58587a25a9db2fbe3a3c98678721a9a22d0f0456a1c06263d02d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
